### ISSUE TITLE
You mother fucker asshole cum drinker ass eater

### ISSUE THREAD

**Issue by jinja365** [mackoz0x98/vape#2]
I AM CHILD SORRY FOR MY ISSUE DADDY.

**Comment by mackoz0x98** [comment]
OK. You download free cracks and your pc downed by pepegas! Good luck kid.

**Comment by PndaBoi** [comment]
imagine copy pasting the same comment onto another issue

**Comment by mackoz0x98** [comment]
It just shows that I'm not interested in you. My own vape crack diffrent your virus.
![image](https://user-images.githubusercontent.com/63849695/160248997-dbeaad98-a6ea-4250-a45c-c0fd018629be.png)
